// grwsup.h - file types supported by this version of the library
#if !defined(GRWSUPP_H)
#define GRWSUPP_H
#if 1
#define G42_READ_IMAGES
#define G42_READ_BMP
#define G42_READ_EPS
#define G42_READ_GIF
#define G42_READ_JPEG
#define G42_READ_PBM
#define G42_READ_PCX
#define G42_READ_PNG
#define G42_READ_RAS
#define G42_READ_TARGA
#define G42_READ_TIFF
#define G42_READ_XWD
#endif
#if 0
#define G42_WRITE_IMAGES
#define G42_WRITE_BMP
#define G42_WRITE_EPS
#define G42_WRITE_GIF
#define G42_WRITE_JPEG
#define G42_WRITE_PBM
#define G42_WRITE_PCX
#define G42_WRITE_PNG
#define G42_WRITE_RAS
#define G42_WRITE_TARGA
#define G42_WRITE_TIFF
#define G42_WRITE_XWD
#endif
#if 0
#define G42_READ_SOUNDS
#define G42_WRITE_SOUNDS
#define G42_READ_WAVE
#define G42_READ_AIFF
#define G42_READ_PCM
#define G42_READ_AU
//#define G42_WRITE_WAVE
//#define G42_WRITE_AIFF
#define G42_WRITE_PCM
#define G42_WRITE_AU
#define G42_WRITE_RA
#endif
#endif // GRWSUPP_H
